// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWIHbrfpMM8oKJY9ob-31y_owZBOKgjw',
    appId: '1:617599580896:web:171d7e1013b26e563e2e85',
    messagingSenderId: '617599580896',
    projectId: 'servease-485fa',
    authDomain: 'servease-485fa.firebaseapp.com',
    storageBucket: 'servease-485fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxbL0GFtpFYMU10GDoJ1HqqfPwF7Mb0Kg',
    appId: '1:617599580896:android:5f98a42e266097893e2e85',
    messagingSenderId: '617599580896',
    projectId: 'servease-485fa',
    storageBucket: 'servease-485fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhLQAkgOH2nhXOy38RSA_SLmwBw0YH-3A',
    appId: '1:617599580896:ios:9e060b332e14e0dd3e2e85',
    messagingSenderId: '617599580896',
    projectId: 'servease-485fa',
    storageBucket: 'servease-485fa.firebasestorage.app',
    iosBundleId: 'com.example.serveaseWorker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhLQAkgOH2nhXOy38RSA_SLmwBw0YH-3A',
    appId: '1:617599580896:ios:9e060b332e14e0dd3e2e85',
    messagingSenderId: '617599580896',
    projectId: 'servease-485fa',
    storageBucket: 'servease-485fa.firebasestorage.app',
    iosBundleId: 'com.example.serveaseWorker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWIHbrfpMM8oKJY9ob-31y_owZBOKgjw',
    appId: '1:617599580896:web:e593aa251f1b25f93e2e85',
    messagingSenderId: '617599580896',
    projectId: 'servease-485fa',
    authDomain: 'servease-485fa.firebaseapp.com',
    storageBucket: 'servease-485fa.firebasestorage.app',
  );

}